### ISSUE TITLE
Can't add tools interactively to experiment

### ISSUE THREAD

**Issue by osolich** [pdonald/iems#1]
It is no longer possible to add tools from the toolbox to the experiment by drag and drop and selecting tools to change properties or remove.

**Comment by pdonald** [comment]
Are you using Firefox? Drag and drop works for me in Chrome, IE11 and Edge but not Firefox.

You should be able to select multiple boxes by selecting an area with your mouse. You should be able to see/edit the properties of the tool you selected last. To remove the selected tools just press Delete.

![select](https://cloud.githubusercontent.com/assets/860965/10178409/1e6a7a56-6708-11e5-9d16-1385ffc3961f.gif)

But I haven't started thinking about design and user experience.

**Comment by osolich** [comment]
I see, you changed from selecting per click to selecting by dragging an area. After selecting a tool now I can put a tool from the toolbox to the experiment. (Before selecting it is not possible.)
Thank you!

PS: I use Chrome and Windows.
